### ISSUE TITLE
Anaklasis is failing several ORSO validation tests

### ISSUE THREAD

**Issue by andyfaff** [alexandros-koutsioumpas/anaklasis#1]
I'm trying to add `anaklasis` to the ORSO validation tests that verify reflectivity calculations for various packages, https://github.com/reflectivity/analysis/pull/58. At the moment several of the validation tests are failing.

There are three unsmeared calculations that don't work and two smeared calculations.

- Can you check to see if I am doing the [smeared calculation](https://github.com/reflectivity/analysis/pull/58/files#diff-11927df1181031b6766fc20bd06f16d0fec461cf770b14f2d16d4975c8562f11R92) correctly? The `dq` that the validation tests use is a standard deviation of a gaussian distribution, what does `anaklasis` use for the `res_bin` argument of the `ref.Reflectivity` function? Is it a standard deviation or a FWHM /etc?
- I would prefer to use the `anaklasis.calculate` function for these comparisons, but it appears there is no way to pass in a set of q values that you need the reflectivity calculated for.
- the fail in the unsmeared calculations may be due to the wrong branch of a complex square root being chosen.

Separately:
- the docstring for `resolution` argument for the `ref.calculate` function could definitely be improved, because it's not clear what kind of dq value is required (standard deviation/FWHM/etc).

**Comment by alexandros-koutsioumpas** [comment]
Post vacations investigation showed that there was a bug in the previous version of the package that was leading to the validation failure and has been corrected in _version 1.5_. *dQ* represents the FWHM (the package documentation has been updated to include this info).

For the validation script:

assuming that the ```data[:,3]``` contains dQ (FWHM) resolution of each corresponding Q point, use the following code for the calculation.

```python
use_dq = -1
tmp = ref.Reflectivity(q, dq, [layer_matrix], use_dq, 0, 1, patches, 1)
```

Although that for the moment the Reflectivity function is not meant to be used externally by users, brief comments have been included regarding input. In a coming version, a proper function for reflectivity calculations for a desired range of Q points will be provided.

**Comment by andyfaff** [comment]
I'll update the resolution function aspects soon. However, there are also a few issues with the [unsmeared reflectivity calculation](https://github.com/reflectivity/analysis/runs/3410147346?check_suite_focus=true). Specifically tests 0, 1, 6.
Those tests are [here](https://github.com/reflectivity/analysis/tree/master/validation/test/unpolarised).

**Comment by andyfaff** [comment]
I updated the code with your suggestions for resolution smearing. However, tests: 0, 1, 4, 5, and 6 are still failing.

**Comment by alexandros-koutsioumpas** [comment]
As of version 1.5.1 a bug related to a wrong branch of complex sqrt calculations has been corrected. In principle all "unsmeared" tests now should run giving a relative error in reflectivity smaller than 8e-5.

**Comment by alexandros-koutsioumpas** [comment]
I noticed with local tests that version 1.5.1 of `anaklasis` cannot pass test #5 although test #1 (unsmeared) for the  same structure is successful. I suspect this is due to the fact that in `anaklasis` the Gaussian resolution convolution limits are from -4*sigma to +4*sigma and the reflectivity data in file `data5.dat` were calculated using -3.5*sigma to +3.5*sigma limits (as evidenced by the reflectivity value 0.9995 below Qc). Temporarily in version 1.5.2 of `anaklasis` I will use -3.5*sigma to +3.5*sigma limits, but I think this is a point worth discussing at the ORSO analysis forum.

**Comment by andyfaff** [comment]
The anaklasis validation is now passing, https://github.com/reflectivity/analysis/pull/58/checks?check_run_id=3427866549. I'm guessing that's for anaklasis.version 1.5.2.

The wrong branch of the complex sqrt is a subtle thing that's been missed by several packages (including Motofit) in the past, so don't worry too much.

The validation tolerances are relaxed on purpose for the resolution smearing, just because of the various smearing approaches that are possible. It might be worth relaxing them further. I went with -3.5 to 3.5 sigma because it's very close to 1 below Qc. It was more of an empirical choice. However, one doesn't want to go too far out, because one doesn't want to place too many numerical integration points out where they have least effect; i.e. you want high density where P(Q) * R(Q) is larger.

**Comment by andyfaff** [comment]
Including the orso validation in your own CI test suite might prove beneficial. 
Given that it runs weekly it's already found issues when packages have made changes that don't work.

**Comment by alexandros-koutsioumpas** [comment]
Good, in the next version of the package, the validation tests will be included in the provided test script.

**Comment by alexandros-koutsioumpas** [comment]
Also if possible it would be nice to be able to put a badge in the readme file of the package, that gives the info about if the analysis tests are passed or not. However I am not aware how such a thing can be done.

**Comment by andyfaff** [comment]
It's not possible to get an individual badge for the GH Actions run. The only way to do that would be to create a separate CI file for each package. I get informed when the validation fails, because the validation also runs on a weekly basis on my fork.
Perhaps you can add an entry in your CI to clone the validation repo, then run the relevant script for anaklasis. Then you know that your codebase is passing the validation.
